export interface DefaultExerciseSeed {
    id: string
    nombre: string
    grupoMuscularPrimario: string
    equipoNecesario: string
}

export const defaultExercises: DefaultExerciseSeed[] = [
    { id: 'pecho-press-banca', nombre: 'Press de banca', grupoMuscularPrimario: 'pecho', equipoNecesario: 'barra' },
    { id: 'pecho-press-inclinado-mancuernas', nombre: 'Press inclinado con mancuernas', grupoMuscularPrimario: 'pecho', equipoNecesario: 'mancuernas' },
    { id: 'pecho-press-declinado', nombre: 'Press declinado', grupoMuscularPrimario: 'pecho', equipoNecesario: 'barra' },
    { id: 'pecho-aperturas-mancuernas', nombre: 'Aperturas con mancuernas', grupoMuscularPrimario: 'pecho', equipoNecesario: 'mancuernas' },
    { id: 'pecho-cruce-poleas', nombre: 'Cruce de poleas', grupoMuscularPrimario: 'pecho', equipoNecesario: 'cable' },
    { id: 'pecho-press-maquina', nombre: 'Press de pecho en máquina', grupoMuscularPrimario: 'pecho', equipoNecesario: 'maquina' },
    { id: 'pecho-flexiones', nombre: 'Flexiones', grupoMuscularPrimario: 'pecho', equipoNecesario: 'peso corporal' },
    { id: 'pecho-fondos', nombre: 'Fondos en paralelas', grupoMuscularPrimario: 'pecho', equipoNecesario: 'peso corporal' },
    { id: 'espalda-dominadas', nombre: 'Dominadas', grupoMuscularPrimario: 'espalda', equipoNecesario: 'peso corporal' },
    { id: 'espalda-jalon-pecho', nombre: 'Jalón al pecho', grupoMuscularPrimario: 'espalda', equipoNecesario: 'maquina' },
    { id: 'espalda-remo-barra', nombre: 'Remo con barra', grupoMuscularPrimario: 'espalda', equipoNecesario: 'barra' },
    { id: 'espalda-remo-mancuerna', nombre: 'Remo con mancuerna', grupoMuscularPrimario: 'espalda', equipoNecesario: 'mancuernas' },
    { id: 'espalda-remo-polea', nombre: 'Remo en polea baja', grupoMuscularPrimario: 'espalda', equipoNecesario: 'cable' },
    { id: 'espalda-facepull', nombre: 'Face pull', grupoMuscularPrimario: 'espalda', equipoNecesario: 'cable' },
    { id: 'espalda-peso-muerto', nombre: 'Peso muerto', grupoMuscularPrimario: 'espalda', equipoNecesario: 'barra' },
    { id: 'espalda-encogimientos', nombre: 'Encogimientos de trapecio', grupoMuscularPrimario: 'espalda', equipoNecesario: 'mancuernas' },
    { id: 'pierna-sentadilla-trasera', nombre: 'Sentadilla trasera', grupoMuscularPrimario: 'piernas', equipoNecesario: 'barra' },
    { id: 'pierna-sentadilla-frontal', nombre: 'Sentadilla frontal', grupoMuscularPrimario: 'piernas', equipoNecesario: 'barra' },
    { id: 'pierna-prensa', nombre: 'Prensa de piernas', grupoMuscularPrimario: 'piernas', equipoNecesario: 'maquina' },
    { id: 'pierna-zancadas', nombre: 'Zancadas caminando', grupoMuscularPrimario: 'piernas', equipoNecesario: 'mancuernas' },
    { id: 'pierna-bulgaras', nombre: 'Sentadilla búlgara', grupoMuscularPrimario: 'piernas', equipoNecesario: 'mancuernas' },
    { id: 'pierna-peso-rumano', nombre: 'Peso muerto rumano', grupoMuscularPrimario: 'piernas', equipoNecesario: 'barra' },
    { id: 'pierna-hip-thrust', nombre: 'Hip thrust', grupoMuscularPrimario: 'piernas', equipoNecesario: 'barra' },
    { id: 'pierna-extension-cuadriceps', nombre: 'Extensión de cuádriceps', grupoMuscularPrimario: 'piernas', equipoNecesario: 'maquina' },
    { id: 'pierna-curl-femoral', nombre: 'Curl femoral', grupoMuscularPrimario: 'piernas', equipoNecesario: 'maquina' },
    { id: 'pierna-elevacion-gemelos', nombre: 'Elevación de gemelos', grupoMuscularPrimario: 'piernas', equipoNecesario: 'maquina' },
    { id: 'hombro-press-militar', nombre: 'Press militar', grupoMuscularPrimario: 'hombros', equipoNecesario: 'barra' },
    { id: 'hombro-press-arnold', nombre: 'Press Arnold', grupoMuscularPrimario: 'hombros', equipoNecesario: 'mancuernas' },
    { id: 'hombro-elevacion-lateral', nombre: 'Elevaciones laterales', grupoMuscularPrimario: 'hombros', equipoNecesario: 'mancuernas' },
    { id: 'hombro-elevacion-frontal', nombre: 'Elevaciones frontales', grupoMuscularPrimario: 'hombros', equipoNecesario: 'mancuernas' },
    { id: 'hombro-pajaro', nombre: 'Pájaros', grupoMuscularPrimario: 'hombros', equipoNecesario: 'mancuernas' },
    { id: 'hombro-remo-menton', nombre: 'Remo al mentón', grupoMuscularPrimario: 'hombros', equipoNecesario: 'barra' },
    { id: 'hombro-maquina', nombre: 'Press hombro en máquina', grupoMuscularPrimario: 'hombros', equipoNecesario: 'maquina' },
    { id: 'biceps-curl-barra', nombre: 'Curl de bíceps con barra', grupoMuscularPrimario: 'biceps', equipoNecesario: 'barra' },
    { id: 'biceps-curl-mancuernas', nombre: 'Curl alterno con mancuernas', grupoMuscularPrimario: 'biceps', equipoNecesario: 'mancuernas' },
    { id: 'biceps-curl-martillo', nombre: 'Curl martillo', grupoMuscularPrimario: 'biceps', equipoNecesario: 'mancuernas' },
    { id: 'biceps-curl-banco-scott', nombre: 'Curl en banco Scott', grupoMuscularPrimario: 'biceps', equipoNecesario: 'maquina' },
    { id: 'biceps-curl-cable', nombre: 'Curl en polea', grupoMuscularPrimario: 'biceps', equipoNecesario: 'cable' },
    { id: 'biceps-concentrado', nombre: 'Curl concentrado', grupoMuscularPrimario: 'biceps', equipoNecesario: 'mancuernas' },
    { id: 'triceps-press-frances', nombre: 'Press francés', grupoMuscularPrimario: 'triceps', equipoNecesario: 'barra' },
    { id: 'triceps-extension-polea', nombre: 'Extensión de tríceps en polea', grupoMuscularPrimario: 'triceps', equipoNecesario: 'cable' },
    { id: 'triceps-fondos-banco', nombre: 'Fondos en banco', grupoMuscularPrimario: 'triceps', equipoNecesario: 'peso corporal' },
    { id: 'triceps-patada', nombre: 'Patada de tríceps', grupoMuscularPrimario: 'triceps', equipoNecesario: 'mancuernas' },
    { id: 'triceps-overhead-mancuerna', nombre: 'Extensión overhead con mancuerna', grupoMuscularPrimario: 'triceps', equipoNecesario: 'mancuernas' },
    { id: 'triceps-copa-cable', nombre: 'Extensión de tríceps con cuerda', grupoMuscularPrimario: 'triceps', equipoNecesario: 'cable' },
    { id: 'core-plancha', nombre: 'Plancha frontal', grupoMuscularPrimario: 'core', equipoNecesario: 'peso corporal' },
    { id: 'core-plancha-lateral', nombre: 'Plancha lateral', grupoMuscularPrimario: 'core', equipoNecesario: 'peso corporal' },
    { id: 'core-crunch', nombre: 'Crunch abdominal', grupoMuscularPrimario: 'core', equipoNecesario: 'peso corporal' },
    { id: 'core-rueda', nombre: 'Ab wheel rollout', grupoMuscularPrimario: 'core', equipoNecesario: 'accesorio' },
    { id: 'core-elevacion-piernas', nombre: 'Elevación de piernas', grupoMuscularPrimario: 'core', equipoNecesario: 'peso corporal' },
    { id: 'core-mountain-climbers', nombre: 'Mountain climbers', grupoMuscularPrimario: 'core', equipoNecesario: 'peso corporal' },
    { id: 'core-russian-twist', nombre: 'Russian twist', grupoMuscularPrimario: 'core', equipoNecesario: 'mancuernas' },
    { id: 'core-dead-bug', nombre: 'Dead bug', grupoMuscularPrimario: 'core', equipoNecesario: 'peso corporal' },
    { id: 'core-hollow-hold', nombre: 'Hollow hold', grupoMuscularPrimario: 'core', equipoNecesario: 'peso corporal' },
    { id: 'core-crunch-cable', nombre: 'Crunch en polea', grupoMuscularPrimario: 'core', equipoNecesario: 'cable' },
]
