import type { Exercise } from '../types/models'

type SeedExercise = Omit<Exercise, 'id' | 'createdAt' | 'updatedAt'>

export const seedExercises: SeedExercise[] = [
  {
    nombre: 'Press de banca',
    descripcion: 'Empuje horizontal con barra para pectoral y tríceps.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['hombros', 'triceps'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Mantén escápulas retraídas y controla el descenso.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press inclinado con mancuernas',
    descripcion: 'Trabajo superior de pectoral con mancuernas.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['hombros', 'triceps'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Baja hasta 90° de codo y empuja en línea controlada.',
    esPersonalizado: false,
  },
  {
    nombre: 'Dominadas',
    descripcion: 'Tracción vertical para dorsales y bíceps.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['biceps', 'core'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Inicia colgado, pecho al frente y controla la bajada.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo con barra',
    descripcion: 'Tracción horizontal para densidad de espalda.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['biceps', 'hombros'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Espalda neutra y codos pegados al cuerpo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Sentadilla trasera',
    descripcion: 'Patrón dominante de rodilla para tren inferior.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['gluteos', 'core'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Desciende manteniendo tronco firme y rodillas estables.',
    esPersonalizado: false,
  },
  {
    nombre: 'Prensa de piernas',
    descripcion: 'Trabajo guiado para cuádriceps y glúteos.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['gluteos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Controla el rango y evita bloquear rodillas.',
    esPersonalizado: false,
  },
  {
    nombre: 'Peso muerto rumano',
    descripcion: 'Bisagra de cadera para femorales y glúteos.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['espalda', 'core'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Mantén barra cerca del cuerpo y espalda neutra.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press militar',
    descripcion: 'Empuje vertical para hombros y tríceps.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['triceps', 'core'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Glúteos contraídos y evita arquear la zona lumbar.',
    esPersonalizado: false,
  },
  {
    nombre: 'Elevaciones laterales',
    descripcion: 'Aislamiento del deltoides medio.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Eleva hasta línea de hombros con codos suaves.',
    esPersonalizado: false,
  },
  {
    nombre: 'Curl de bíceps con barra',
    descripcion: 'Flexión de codo para bíceps braquial.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: ['antebrazos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'barra',
    instrucciones: 'No balancees el tronco y controla el descenso.',
    esPersonalizado: false,
  },
  {
    nombre: 'Fondos en paralelas',
    descripcion: 'Empuje para tríceps y pectoral inferior.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: ['pecho', 'hombros'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Desciende con control y evita encoger hombros.',
    esPersonalizado: false,
  },
  {
    nombre: 'Extensión de tríceps en polea',
    descripcion: 'Aislamiento de tríceps con polea.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Mantén codos fijos y extiende completamente.',
    esPersonalizado: false,
  },
  {
    nombre: 'Crunch abdominal',
    descripcion: 'Flexión de tronco para recto abdominal.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Eleva el tronco sin tirar del cuello.',
    esPersonalizado: false,
  },
  {
    nombre: 'Plancha frontal',
    descripcion: 'Estabilidad isométrica de core.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['hombros', 'gluteos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Mantén alineación cabeza-cadera-talones.',
    esPersonalizado: false,
  },
  {
    nombre: 'Hip thrust',
    descripcion: 'Empuje de cadera para glúteos.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['core'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Pausa arriba y evita hiperextender lumbar.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press declinado con barra',
    descripcion: 'Empuje orientado al pectoral inferior.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['triceps', 'hombros'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Controla el descenso y no rebotes en el pecho.',
    esPersonalizado: false,
  },
  {
    nombre: 'Aperturas con mancuernas',
    descripcion: 'Aislamiento de pectoral en banco plano.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Mantén codos semiflexionados y rango controlado.',
    esPersonalizado: false,
  },
  {
    nombre: 'Cruce de poleas',
    descripcion: 'Trabajo de aducción horizontal para pectoral.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Cruza manos al frente y aprieta al final.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press de pecho en máquina',
    descripcion: 'Empuje guiado para pectoral.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['triceps'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Ajusta asiento y empuja con control.',
    esPersonalizado: false,
  },
  {
    nombre: 'Flexiones',
    descripcion: 'Empuje con peso corporal para pectoral.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['triceps', 'core'],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Cuerpo alineado y pecho cerca del suelo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Pullover con mancuerna',
    descripcion: 'Movimiento complementario para caja torácica y pectoral.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['espalda'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Desciende detrás de la cabeza con control.',
    esPersonalizado: false,
  },
  {
    nombre: 'Dominadas supinas',
    descripcion: 'Tracción vertical con énfasis en bíceps y dorsales.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['brazos', 'core'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Inicia colgado y sube pecho a la barra.',
    esPersonalizado: false,
  },
  {
    nombre: 'Jalón al pecho',
    descripcion: 'Alternativa guiada a dominadas para dorsales.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['biceps'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Lleva barra al pecho sin balancear torso.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo en polea baja',
    descripcion: 'Tracción horizontal para espalda media.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['biceps', 'hombros'],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Tira hacia el ombligo y retrae escápulas.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo con mancuerna a una mano',
    descripcion: 'Trabajo unilateral de dorsales.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['biceps', 'core'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Espalda neutra y tracción hacia la cadera.',
    esPersonalizado: false,
  },
  {
    nombre: 'Face pull',
    descripcion: 'Trabajo de deltoide posterior y trapecio.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Lleva cuerda hacia la cara con codos altos.',
    esPersonalizado: false,
  },
  {
    nombre: 'Peso muerto convencional',
    descripcion: 'Levantamiento total con énfasis en cadena posterior.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['piernas', 'core'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'barra',
    instrucciones: 'Mantén la barra pegada al cuerpo y espalda neutra.',
    esPersonalizado: false,
  },
  {
    nombre: 'Encogimientos de trapecio',
    descripcion: 'Aislamiento para trapecio superior.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Eleva hombros verticalmente sin rotarlos.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo T-bar',
    descripcion: 'Tracción pesada para densidad dorsal.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['biceps'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Tronco estable y tirón hacia el esternón.',
    esPersonalizado: false,
  },
  {
    nombre: 'Sentadilla frontal',
    descripcion: 'Variante de sentadilla con mayor énfasis en cuádriceps.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['core', 'gluteos'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Codos altos y torso erguido durante toda la serie.',
    esPersonalizado: false,
  },
  {
    nombre: 'Zancadas caminando',
    descripcion: 'Trabajo unilateral para piernas y glúteos.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['gluteos', 'core'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Da pasos largos y controla la rodilla delantera.',
    esPersonalizado: false,
  },
  {
    nombre: 'Búlgaras',
    descripcion: 'Sentadilla unilateral con pie trasero elevado.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['gluteos', 'core'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Mantén equilibrio y desciende en vertical.',
    esPersonalizado: false,
  },
  {
    nombre: 'Extensión de cuádriceps',
    descripcion: 'Aislamiento para cuádriceps.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Extiende completamente y baja controlado.',
    esPersonalizado: false,
  },
  {
    nombre: 'Curl femoral tumbado',
    descripcion: 'Aislamiento de isquiotibiales.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'No levantes la cadera del banco.',
    esPersonalizado: false,
  },
  {
    nombre: 'Peso muerto sumo',
    descripcion: 'Bisagra amplia con énfasis en aductores y glúteo.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['espalda', 'core'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'barra',
    instrucciones: 'Pies abiertos y rodillas siguiendo puntas.',
    esPersonalizado: false,
  },
  {
    nombre: 'Step up',
    descripcion: 'Subida al cajón para fuerza unilateral.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['gluteos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Impúlsate con la pierna de apoyo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Elevación de gemelos de pie',
    descripcion: 'Trabajo de pantorrilla en apoyo.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Recorre todo el rango del tobillo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Elevación de gemelos sentado',
    descripcion: 'Aislamiento de sóleo.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Pausa arriba y baja lento.',
    esPersonalizado: false,
  },
  {
    nombre: 'Buenos días',
    descripcion: 'Bisagra de cadera con barra para posterior.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['core', 'espalda'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'barra',
    instrucciones: 'Hinge de cadera manteniendo espalda neutra.',
    esPersonalizado: false,
  },
  {
    nombre: 'Sentadilla goblet',
    descripcion: 'Sentadilla con mancuerna al pecho.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['core', 'gluteos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Mantén codos dentro y pecho abierto.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press Arnold',
    descripcion: 'Empuje de hombro con rotación.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['triceps'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Rota controladamente durante el empuje.',
    esPersonalizado: false,
  },
  {
    nombre: 'Pájaros con mancuernas',
    descripcion: 'Aislamiento de deltoide posterior.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['espalda'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Tórax inclinado y brazo en arco amplio.',
    esPersonalizado: false,
  },
  {
    nombre: 'Elevación frontal',
    descripcion: 'Aislamiento de deltoide anterior.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Eleva hasta altura de hombros sin impulso.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press push press',
    descripcion: 'Empuje de hombro con asistencia de piernas.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['piernas', 'triceps'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'barra',
    instrucciones: 'Usa una ligera flexión de rodillas para impulsar.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo al mentón',
    descripcion: 'Trabajo de deltoide y trapecio.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['espalda'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Sube codos y mantén muñecas neutrales.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press de hombro en máquina',
    descripcion: 'Empuje vertical guiado.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['triceps'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'No bloquees codos al finalizar.',
    esPersonalizado: false,
  },
  {
    nombre: 'Curl inclinado con mancuernas',
    descripcion: 'Aislamiento de bíceps con estiramiento.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: ['antebrazos'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Evita mover hombros durante el curl.',
    esPersonalizado: false,
  },
  {
    nombre: 'Curl martillo',
    descripcion: 'Trabajo de braquial y braquiorradial.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: ['antebrazos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Agarre neutro y control total.',
    esPersonalizado: false,
  },
  {
    nombre: 'Curl en polea baja',
    descripcion: 'Tensión continua para bíceps.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Mantén codos fijos al costado.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press francés',
    descripcion: 'Extensión de tríceps con barra.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Baja barra controlada hacia la frente.',
    esPersonalizado: false,
  },
  {
    nombre: 'Extensión de tríceps por encima de la cabeza',
    descripcion: 'Enfoque en porción larga del tríceps.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Codos cerca de la cabeza durante toda la serie.',
    esPersonalizado: false,
  },
  {
    nombre: 'Patada de tríceps',
    descripcion: 'Aislamiento de tríceps en extensión final.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Brazo paralelo al suelo y extensión completa.',
    esPersonalizado: false,
  },
  {
    nombre: 'Curl inverso',
    descripcion: 'Trabajo de bíceps y antebrazo con agarre prono.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: ['antebrazos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'barra',
    instrucciones: 'No balancees torso y sube con control.',
    esPersonalizado: false,
  },
  {
    nombre: 'Rueda abdominal',
    descripcion: 'Antiextensión avanzada de core.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'rueda abdominal',
    instrucciones: 'Mantén pelvis estable y evita colapsar lumbar.',
    esPersonalizado: false,
  },
  {
    nombre: 'Elevaciones de piernas colgado',
    descripcion: 'Trabajo intenso de abdomen inferior.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['brazos'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Eleva piernas sin balancear el cuerpo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Pallof press',
    descripcion: 'Antirotación para estabilidad del core.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Mantén el tronco estable y brazos extendidos.',
    esPersonalizado: false,
  },
  {
    nombre: 'Crunch en polea',
    descripcion: 'Flexión de tronco con resistencia.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Contrae abdominales llevando costillas a pelvis.',
    esPersonalizado: false,
  },
  {
    nombre: 'Plancha lateral',
    descripcion: 'Estabilidad lateral del tronco.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['hombros', 'gluteos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Mantén cuerpo en línea y cadera elevada.',
    esPersonalizado: false,
  },
  {
    nombre: 'Bird dog',
    descripcion: 'Control lumbopélvico y estabilidad.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['espalda', 'gluteos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Extiende brazo y pierna opuestos sin rotar.',
    esPersonalizado: false,
  },
  {
    nombre: 'Russian twist',
    descripcion: 'Trabajo de oblicuos con rotación.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Rota tronco manteniendo abdomen activo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Hollow body hold',
    descripcion: 'Isométrico para control global del core.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Espalda lumbar pegada al suelo todo el tiempo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo invertido en barra',
    descripcion: 'Tracción horizontal con peso corporal.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['brazos', 'core'],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Cuerpo recto y pecho hacia la barra.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press de banca con pausa',
    descripcion: 'Variante de control para mejorar fuerza inicial.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['triceps'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'barra',
    instrucciones: 'Pausa 1 segundo en el pecho antes de empujar.',
    esPersonalizado: false,
  },
  {
    nombre: 'Hack squat',
    descripcion: 'Sentadilla guiada para cuádriceps.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['gluteos'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'maquina',
    instrucciones: 'Mantén espalda apoyada y controla profundidad.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo pendlay',
    descripcion: 'Remo explosivo desde el suelo.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['biceps'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'barra',
    instrucciones: 'Cada repetición parte desde el suelo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Landmine press',
    descripcion: 'Empuje diagonal para hombro y core.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['core', 'pecho'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Empuja en diagonal manteniendo tronco firme.',
    esPersonalizado: false,
  },
  {
    nombre: 'Sissy squat',
    descripcion: 'Aislamiento de cuádriceps con peso corporal.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['core'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Mantén cadera extendida y rodillas controladas.',
    esPersonalizado: false,
  },
  {
    nombre: 'Farmer walk',
    descripcion: 'Caminata cargada para core y agarre.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['espalda', 'brazos'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Camina erguido con tensión en todo el cuerpo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Aducción en máquina',
    descripcion: 'Trabajo de aductores de cadera.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Cierra piernas con control y pausa final.',
    esPersonalizado: false,
  },
  {
    nombre: 'Abducción en máquina',
    descripcion: 'Trabajo de glúteo medio.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['core'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Abre piernas sin inclinar el torso.',
    esPersonalizado: false,
  },
  {
    nombre: 'Pulldown con agarre estrecho',
    descripcion: 'Tracción vertical para dorsales bajos.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['brazos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Lleva maneral al pecho sin balancear.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press cerrado',
    descripcion: 'Empuje para tríceps con barra.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: ['pecho'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Agarre más estrecho que hombros y codos pegados.',
    esPersonalizado: false,
  },
  {
    nombre: 'Fondos en banco',
    descripcion: 'Extensión de tríceps con peso corporal.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Baja controlado sin sobrecargar hombro.',
    esPersonalizado: false,
  },
  {
    nombre: 'Curl concentrado',
    descripcion: 'Aislamiento unilateral de bíceps.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Apoya codo en muslo y sube sin impulso.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo pecho apoyado',
    descripcion: 'Tracción horizontal reduciendo carga lumbar.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['biceps'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Pecho en banco inclinado y tracción limpia.',
    esPersonalizado: false,
  },
  {
    nombre: 'Sentadilla en multipower',
    descripcion: 'Variante guiada de sentadilla.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['gluteos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Posición de pies estable y descenso controlado.',
    esPersonalizado: false,
  },
  {
    nombre: 'Peso muerto a una pierna',
    descripcion: 'Bisagra unilateral para estabilidad y glúteo.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['core'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Mantén cadera alineada y espalda neutra.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press de hombros con mancuernas sentado',
    descripcion: 'Empuje vertical sentado para estabilidad.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['triceps'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'No arquees la espalda al empujar.',
    esPersonalizado: false,
  },
  {
    nombre: 'Elevación lateral en polea',
    descripcion: 'Tensión continua del deltoide medio.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'cable',
    instrucciones: 'Cruza polea por delante y eleva lateralmente.',
    esPersonalizado: false,
  },
  {
    nombre: 'Y-raise en banco inclinado',
    descripcion: 'Trabajo de manguito y deltoide superior.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['espalda'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Eleva brazos en forma de Y con poco peso.',
    esPersonalizado: false,
  },
  {
    nombre: 'Plank con desplazamiento',
    descripcion: 'Core dinámico con inestabilidad.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Desplaza manos sin perder alineación.',
    esPersonalizado: false,
  },
  {
    nombre: 'Dead bug',
    descripcion: 'Control de core y coordinación.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Extiende extremidades opuestas con lumbar neutra.',
    esPersonalizado: false,
  },
  {
    nombre: 'Sit up',
    descripcion: 'Flexión completa de tronco.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['flexores de cadera'],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Sube vértebra a vértebra y controla bajada.',
    esPersonalizado: false,
  },
  {
    nombre: 'Mountain climbers',
    descripcion: 'Core dinámico y trabajo cardiovascular.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['hombros', 'piernas'],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Mantén ritmo constante sin hundir la cadera.',
    esPersonalizado: false,
  },
  {
    nombre: 'Pulldown brazos rectos',
    descripcion: 'Aislamiento de dorsales con brazos extendidos.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['core'],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Baja barra con brazos casi rectos.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press de pecho con mancuernas neutras',
    descripcion: 'Empuje horizontal con agarre neutro.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['triceps'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Mantén muñecas neutras y baja con control.',
    esPersonalizado: false,
  },
  {
    nombre: 'Aperturas en peck-deck',
    descripcion: 'Aislamiento guiado de pectoral.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Aprieta al centro y controla el regreso.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press inclinado en máquina',
    descripcion: 'Empuje inclinado guiado para pectoral superior.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['hombros', 'triceps'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Empuja sin bloquear codos.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo en máquina convergente',
    descripcion: 'Tracción guiada unilateral para espalda.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['biceps'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Mantén pecho apoyado y tracción simétrica.',
    esPersonalizado: false,
  },
  {
    nombre: 'Dominadas asistidas',
    descripcion: 'Progresión de dominadas con soporte.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['brazos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Disminuye asistencia progresivamente.',
    esPersonalizado: false,
  },
  {
    nombre: 'Puente de glúteos',
    descripcion: 'Extensión de cadera para glúteo.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['core'],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Empuja talones y aprieta glúteos arriba.',
    esPersonalizado: false,
  },
  {
    nombre: 'Peso muerto trap bar',
    descripcion: 'Variante de peso muerto más amigable para lumbar.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['espalda', 'core'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra hexagonal',
    instrucciones: 'Mantén torso neutro y empuja con piernas.',
    esPersonalizado: false,
  },
  {
    nombre: 'Paseo del oso',
    descripcion: 'Locomoción para core y hombros.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['hombros', 'piernas'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Avanza controlando cadera y respiración.',
    esPersonalizado: false,
  },
  {
    nombre: 'Pullover en polea',
    descripcion: 'Extensión de hombro para dorsales.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['core'],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Baja cuerda con brazos extendidos.',
    esPersonalizado: false,
  },
  {
    nombre: 'Elevación de talones en prensa',
    descripcion: 'Trabajo de gemelos usando prensa.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Recorre completo y mantén tensión continua.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press de banca con mancuernas alterno',
    descripcion: 'Empuje unilateral alternado para estabilidad.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['core', 'triceps'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Alterna brazos sin perder estabilidad.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press JM',
    descripcion: 'Híbrido entre press y extensión para tríceps.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: ['pecho'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'barra',
    instrucciones: 'Trayectoria corta y control total de codos.',
    esPersonalizado: false,
  },
  {
    nombre: 'Plancha con peso',
    descripcion: 'Plancha frontal con sobrecarga adicional.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'disco',
    instrucciones: 'Mantén postura neutra durante el tiempo objetivo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo renegado',
    descripcion: 'Remo en plancha para core y espalda.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['core', 'hombros'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Evita rotación de cadera durante cada remo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Thruster',
    descripcion: 'Sentadilla frontal + press por encima de la cabeza.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['hombros', 'core'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'barra',
    instrucciones: 'Encadena sentadilla y press en un solo flujo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Woodchopper en polea',
    descripcion: 'Rotación diagonal para oblicuos.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'cable',
    instrucciones: 'Rota tronco con control de cadera.',
    esPersonalizado: false,
  },
  {
    nombre: 'Push up diamante',
    descripcion: 'Flexión cerrada con énfasis en tríceps.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: ['pecho', 'core'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Manos en triángulo y codos pegados.',
    esPersonalizado: false,
  },
  {
    nombre: 'Sentadilla overhead',
    descripcion: 'Sentadilla con barra sobre la cabeza.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['core', 'hombros'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'barra',
    instrucciones: 'Mantén barra estable y torso erguido.',
    esPersonalizado: false,
  },
  {
    nombre: 'Good morning en máquina',
    descripcion: 'Bisagra guiada para cadena posterior.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['espalda'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'maquina',
    instrucciones: 'Empuja cadera atrás y controla la vuelta.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press de tríceps con cuerda',
    descripcion: 'Extensión en polea con cuerda.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Separa puntas al final del movimiento.',
    esPersonalizado: false,
  },
  {
    nombre: 'Curl de bíceps en banco predicador',
    descripcion: 'Aislamiento estricto de bíceps.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Evita despegar codo del apoyo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo en anillas',
    descripcion: 'Tracción con inestabilidad para espalda.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['core', 'brazos'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'anillas',
    instrucciones: 'Mantén línea corporal durante el tirón.',
    esPersonalizado: false,
  },
  {
    nombre: 'Ab wheel de rodillas',
    descripcion: 'Progresión de rueda abdominal.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'rueda abdominal',
    instrucciones: 'Desplaza adelante sin perder pelvis neutra.',
    esPersonalizado: false,
  },
  {
    nombre: 'Prensa horizontal',
    descripcion: 'Empuje de piernas en plano horizontal.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['gluteos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'No bloquees rodillas al final.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press landmine unilateral',
    descripcion: 'Empuje unilateral para hombro y core.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['core', 'pecho'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'barra',
    instrucciones: 'Estabiliza tronco y empuja en diagonal.',
    esPersonalizado: false,
  },
  {
    nombre: 'Farmer walk unilateral',
    descripcion: 'Paseo cargado de un lado para antiinclinación.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['brazos'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Camina erguido evitando inclinarte.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo en punta con mancuerna',
    descripcion: 'Tracción unilateral en apoyo.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['brazos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Lleva codo hacia la cadera.',
    esPersonalizado: false,
  },
  {
    nombre: 'Push press con mancuernas',
    descripcion: 'Empuje vertical explosivo con mancuernas.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['piernas', 'triceps'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Sincroniza impulso de piernas y press.',
    esPersonalizado: false,
  },
  {
    nombre: 'Cruce de poleas alto-bajo',
    descripcion: 'Aislamiento de pectoral inferior en diagonal.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Traza diagonal de arriba hacia abajo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Cruce de poleas bajo-alto',
    descripcion: 'Aislamiento de pectoral superior en diagonal.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Traza diagonal de abajo hacia arriba.',
    esPersonalizado: false,
  },
  {
    nombre: 'Serrucho en banco',
    descripcion: 'Remo unilateral clásico con mancuerna.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['brazos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Apoya una rodilla en banco y rema controlado.',
    esPersonalizado: false,
  },
  {
    nombre: 'Buenos días con mancuerna',
    descripcion: 'Bisagra de cadera ligera para técnica.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['core'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Recorre rango cómodo sin perder neutralidad.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press cubano',
    descripcion: 'Rotación externa + press para hombro saludable.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['espalda'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Usa cargas ligeras y técnica estricta.',
    esPersonalizado: false,
  },
  {
    nombre: 'Curl spider',
    descripcion: 'Curl de bíceps en banco inclinado boca abajo.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Evita balanceo y controla cada repetición.',
    esPersonalizado: false,
  },
  {
    nombre: 'Plancha con toque de hombros',
    descripcion: 'Core antirotación en apoyo de plancha.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Alterna toques minimizando balanceo lateral.',
    esPersonalizado: false,
  },
  {
    nombre: 'Elevación de cadera en banco',
    descripcion: 'Variante de glúteo sin barra.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['core'],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Empuja con talones y pausa arriba.',
    esPersonalizado: false,
  },
  {
    nombre: 'Paseo del granjero pesado',
    descripcion: 'Trabajo global de fuerza y core.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['espalda', 'brazos'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Camina estable con máxima tensión corporal.',
    esPersonalizado: false,
  },
  {
    nombre: 'Remo unilateral en cable',
    descripcion: 'Tracción aislada por lado para espalda.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['brazos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'cable',
    instrucciones: 'Mantén torso estable durante la tracción.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press de banca con cadenas',
    descripcion: 'Resistencia variable para fuerza explosiva.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['triceps'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'barra',
    instrucciones: 'Mantén trayectoria limpia y controlada.',
    esPersonalizado: false,
  },
  {
    nombre: 'Jalón tras nuca',
    descripcion: 'Variante de jalón con demanda de movilidad.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['hombros'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'cable',
    instrucciones: 'Hazlo solo con movilidad adecuada y control.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press de piernas unilateral',
    descripcion: 'Trabajo unilateral en prensa.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['gluteos'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'maquina',
    instrucciones: 'Mantén cadera estable durante todo el movimiento.',
    esPersonalizado: false,
  },
  {
    nombre: 'Swing con kettlebell',
    descripcion: 'Bisagra explosiva para cadena posterior.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['core', 'espalda'],
    nivelDificultad: 'intermedio',
    equipoNecesario: 'kettlebell',
    instrucciones: 'Impulsa con cadera, no con brazos.',
    esPersonalizado: false,
  },
  {
    nombre: 'Turkish get-up',
    descripcion: 'Patrón completo de estabilidad y control.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['hombros', 'piernas'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'kettlebell',
    instrucciones: 'Realiza cada fase con control técnico.',
    esPersonalizado: false,
  },
  {
    nombre: 'Clean and press',
    descripcion: 'Levantamiento combinado de potencia y empuje.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['piernas', 'core', 'espalda'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'barra',
    instrucciones: 'Coordina tirón, recepción y press sin perder técnica.',
    esPersonalizado: false,
  },
  {
    nombre: 'Toes to bar',
    descripcion: 'Core avanzado en barra.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: ['brazos'],
    nivelDificultad: 'avanzado',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Eleva pies a la barra sin balanceo excesivo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Press de banca en multipower',
    descripcion: 'Empuje guiado para foco en pectoral.',
    grupoMuscularPrimario: 'pecho',
    gruposMuscularesSecundarios: ['triceps'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Ajusta banco y controla rango completo.',
    esPersonalizado: false,
  },
  {
    nombre: 'Pullover en máquina',
    descripcion: 'Trabajo guiado de dorsales.',
    grupoMuscularPrimario: 'espalda',
    gruposMuscularesSecundarios: ['core'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Desciende en arco y aprieta dorsales al final.',
    esPersonalizado: false,
  },
  {
    nombre: 'Split squat',
    descripcion: 'Sentadilla estática unilateral.',
    grupoMuscularPrimario: 'piernas',
    gruposMuscularesSecundarios: ['gluteos'],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Descenso vertical y control de rodilla.',
    esPersonalizado: false,
  },
  {
    nombre: 'Aperturas inversas en peck-deck',
    descripcion: 'Deltoide posterior guiado.',
    grupoMuscularPrimario: 'hombros',
    gruposMuscularesSecundarios: ['espalda'],
    nivelDificultad: 'basico',
    equipoNecesario: 'maquina',
    instrucciones: 'Abre brazos manteniendo control escapular.',
    esPersonalizado: false,
  },
  {
    nombre: 'Curl en banco inclinado alterno',
    descripcion: 'Bíceps unilateral con mayor estiramiento.',
    grupoMuscularPrimario: 'brazos',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'mancuernas',
    instrucciones: 'Alterna brazos sin mover hombro.',
    esPersonalizado: false,
  },
  {
    nombre: 'Crunch bicicleta',
    descripcion: 'Trabajo dinámico de oblicuos y recto abdominal.',
    grupoMuscularPrimario: 'core',
    gruposMuscularesSecundarios: [],
    nivelDificultad: 'basico',
    equipoNecesario: 'peso corporal',
    instrucciones: 'Coordina codo y rodilla opuestos.',
    esPersonalizado: false,
  },
]